#!/bin/bash


## A workaround for MacOS (still) not implementing realpath.
if [[ "$OSTYPE" == "darwin"* ]]; then
    realpath() {
        OURPWD=$PWD
        cd "$(dirname "$1")"
        LINK=$(readlink "$(basename "$1")")
        while [ "$LINK" ]; do
            cd "$(dirname "$LINK")"
            LINK=$(readlink "$(basename "$1")")
        done
        REALPATH="$PWD/$(basename "$1")"
        cd "$OURPWD"
        echo "$REALPATH"
    }
fi

SCRIPT_PATH="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
SCRIPT_DIR=$(dirname $(realpath $0))


#echo "In script PWD:"`pwd`;
#echo "TOOL_HOME: $TOOL_HOME";
java -Djava.util.logging.config.file="$SCRIPT_DIR/jul.properties" -jar "$SCRIPT_DIR"/csv-cruncher-*-single.jar "$@"


## Cleanup
rm -rf ./hsqldb
