#!/bin/bash

SCRIPT_PATH="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
SCRIPT_DIR=`dirname "$SCRIPT_PATH"`


#echo "In script PWD:"`pwd`;
#echo "TOOL_HOME: $TOOL_HOME";
java -Djava.util.logging.config.file="$SCRIPT_DIR/jul.properties" -jar "$SCRIPT_DIR"/csv-cruncher-*-single.jar "$@"


## Cleanup
rm -rf ./hsqldb
